<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="check" nsURI="http://www.svv.lu/offline/check/Check" nsPrefix="check">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore#/"/>
    <details key="oclr" value="oclr.ecore#/"/>
    <details key="trace" value="trace.ecore#/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Monitor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trace" lowerBound="1" eType="ecore:EClass trace.ecore#//Trace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" lowerBound="1"
        eType="ecore:EClass oclr.ecore#//OCLRConstraint"/>
  </eClassifiers>
</ecore:EPackage>
